version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install typescript --location=global
      - npm install
  build:
    commands:
      - tsc

artifacts:
  files:
    - build/**/*
    - public/**/*
    - package.json
    - package-lock.json
    - .ebextensions/**/*